# Generated by Django 5.1.4 on 2025-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
