# Generated by Django 5.1.4 on 2025-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='is_fully_booked',
            field=models.BooleanField(default=False),
        ),
    ]
